site_name: Spt-RST-Project
nav: 
  - Home: index.md
theme:
  name: material
  language: ja
  palette:
    primary: teal
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true

markdown_extensions:
  - meta
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.superfences
  - def_list
  - admonition
  - attr_list
  - codehilite:
      linenums: true
      use_pygments: true