name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: SetUp Python
        run: pip install mkdocs
      - run: pip install mkdocs-material 
      - run: mkdocs build 
      - run: mkdocs gh-deploy --force
